-- MySQL Script generated by MySQL Workbench
-- Sun Dec  6 20:11:11 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dizimo_sagrada_familia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dizimo_sagrada_familia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dizimo_sagrada_familia` DEFAULT CHARACTER SET utf8 ;
USE `dizimo_sagrada_familia` ;

-- -----------------------------------------------------
-- Table `dizimo_sagrada_familia`.`dizimista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dizimo_sagrada_familia`.`dizimista` (
  `id_dizimista` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `data_nascimento` DATE NULL,
  `telefone` VARCHAR(15) NULL,
  `email` VARCHAR(100) NULL,
  `rua` VARCHAR(50) NULL,
  `numero` VARCHAR(6) NULL,
  `bairro` VARCHAR(50) NULL,
  `complemento` VARCHAR(100) NULL,
  `grupo_movimento_pastoral` VARCHAR(100) NULL,
  `data_inscricao` DATE NULL,
  `ativo` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`id_dizimista`))
ENGINE = InnoDB
AUTO_INCREMENT = 3000;


-- -----------------------------------------------------
-- Table `dizimo_sagrada_familia`.`conjuge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dizimo_sagrada_familia`.`conjuge` (
  `dizimista_id_dizimista` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `data_casamento` DATE NOT NULL,
  PRIMARY KEY (`dizimista_id_dizimista`),
  CONSTRAINT `fk_conjuge_dizimista1`
    FOREIGN KEY (`dizimista_id_dizimista`)
    REFERENCES `dizimo_sagrada_familia`.`dizimista` (`id_dizimista`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dizimo_sagrada_familia`.`plantonista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dizimo_sagrada_familia`.`plantonista` (
  `id_plantonista` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(45) NULL,
  `coordenador` TINYINT NOT NULL,
  PRIMARY KEY (`id_plantonista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dizimo_sagrada_familia`.`plantao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dizimo_sagrada_familia`.`plantao` (
  `id_plantao` INT NOT NULL AUTO_INCREMENT,
  `hora` TIME NULL,
  `data` DATE NULL,
  `plantonista_id_plantonista` INT NOT NULL,
  `presidente_id_presidente` INT NOT NULL,
  PRIMARY KEY (`id_plantao`, `plantonista_id_plantonista`, `presidente_id_presidente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dizimo_sagrada_familia`.`contribuicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dizimo_sagrada_familia`.`contribuicao` (
  `id_contribuicao` INT NOT NULL AUTO_INCREMENT,
  `dizimista_id_dizimista` INT NOT NULL,
  `plantonista_id_plantonista` INT NOT NULL,
  `plantao_id_plantao` INT NOT NULL,
  `valor` DOUBLE NULL,
  `mes` ENUM('JAN', 'FEV', 'MAR', 'ABR', 'MAIO', 'JUN', 'JUL', 'AGO', 'SET', 'OUT', 'NOV', 'DEZ') NULL,
  `ano` YEAR NULL,
  PRIMARY KEY (`id_contribuicao`),
  INDEX `fk_contribuicao_plantonista1_idx` (`plantonista_id_plantonista` ASC),
  INDEX `fk_contribuicao_plantao1_idx` (`plantao_id_plantao` ASC),
  INDEX `fk_contribuicao_dizimista1_idx` (`dizimista_id_dizimista` ASC),
  CONSTRAINT `fk_contribuicao_dizimista1`
    FOREIGN KEY (`dizimista_id_dizimista`)
    REFERENCES `dizimo_sagrada_familia`.`dizimista` (`id_dizimista`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_contribuicao_plantonista1`
    FOREIGN KEY (`plantonista_id_plantonista`)
    REFERENCES `dizimo_sagrada_familia`.`plantonista` (`id_plantonista`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_contribuicao_plantao1`
    FOREIGN KEY (`plantao_id_plantao`)
    REFERENCES `dizimo_sagrada_familia`.`plantao` (`id_plantao`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dizimo_sagrada_familia`.`presidente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dizimo_sagrada_familia`.`presidente` (
  `id_presidente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `denominacao` ENUM('PE', 'DIAC', 'MINIS') NULL,
  PRIMARY KEY (`id_presidente`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
